// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nqwhzonvftumpglwozof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5xd2h6b252ZnR1bXBnbHdvem9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjQwMDQsImV4cCI6MjA1ODAwMDAwNH0.i3AzEZ3mhJpxbY4FBr20ZymbA1tIe6CYYLHRVsLEtOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);